### ISSUE TITLE
Improve GSB phased reader

### ISSUE THREAD

**Issue by mhvk** [mhvk/baseband#398]
Problems encountered with trying the GSB reader on real data suggest
- [X] The documentation should more clearly describe what rawdump and phased actually are. That phased files are called `.raw` is not so helpful... Sort-of fixed in #401.
- [X] For some phased data sets, the data do not come split into two files - the code should assume this less, and perhaps passing in a single file should assume the data is from a single polarization. Certainly, the error message should be improved. Fixed in #399.
- [X] `.info` does not work when files are not split (and possibly not on a single polarization if they are). Fixed in #399 
- [X] Make the default for block sizes be 2^22 independent of number of streams, as current data show that for 16.666 MHz with a single stream, it is 2^22. Fixed in #401
- [ ] would be good to do at least a minimal consistency check between the number of headers and the total number of bytes in the raw files.
- [ ] In the docs, encourage passing in all known information, to help with consistency tests.
- [ ] In the docs, a concrete example should be given with four filenames.
- [ ] In the docs, describe sanity checks one could do (which *might* just involve running `fh.info` if `file_info` does those sanity checks!). In particular, checking that `fh.sample_rate * fh.shape[-1]` gives the bandwidth, checking that `fh.stop_time-fh.start_time` is sensible, and that one can read near the end of the file.

(EDIT: updated after #399)
